apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feast-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: feast.kltn.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: feast-online-server
            port:
              number: 6566
