apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: user-interactions
  namespace: kafka
  labels:
    strimzi.io/cluster: recsys-kafka
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 604800000   # 7 ng√†y
    cleanup.policy: delete
