apiVersion: apps/v1
kind: Deployment
metadata:
  name: kltn-api
  labels:
    app: kltn-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kltn-api
  template:
    metadata:
      labels:
        app: kltn-api
    spec:
      containers:
        - name: api
          image: quangtran1011/kltn_api:v5
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: "10.29.49.4"
            - name: MODEL_SERVER_URL
              value: "http://ranker-model-server:3000"
            - name: FEAST_ONLINE_SERVER_HOST
              value: "feast-online-server"
            - name: FEAST_ONLINE_SERVER_PORT
              value: "6566"
      restartPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  name: kltn-api
spec:
  selector:
    app: kltn-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
